# -*- coding: utf-8 -*-
"""
Fonction spécifique au base de données CONTEXA
Ces fonction sont faite par rétro-ingégnerie, sans le support de contexa
Assurez-vous que ces fonctions soient compatible avec votre basse de donnée avant de les utilisées
"""
from __future__ import unicode_literals

import datetime

__author__ = "Charly GONTERO"
__date__ = "2016-01-25 17:56:54"
__version__ = 1.0
__credits__ = """
 *  db_param_seringue.py
 *
 *  Copyright 2011 Charly GONTERO
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 *  MA 02110-1301, USA.
"""

VERSION = __version__
def version():
	return __version__


V4_3_cobra = {
	"id": "IDseringue",
	"num_seringue": "numseringue",
	"type_seringue": "type",
	"num_module": "nummodule",
	"id_ingredient": "IDingredient",
	"visible": "visible",
	"disponible": "disponible",
	"mode_dosage": "modedosage",
	"tol_dose_abs_pos": "toldosabspos",
	"tol_dose_abs_neg": "toldosabsneg",
	"tol_dose_rel_pos": "toldosrelpos",
	"tol_dose_rel_neg": "toldosrelneg",
	"poids maxi": "poidsmaximum",
	"poids_mini": "poidsminimum",
	"mode_erreur": "aftererror",
	"non_dose_stock_mini": "dosageimpossible_al",
	"alarme_reappro": "alarmereappro",
	"alarme_manque": "alarmemanque",
	"alarme_dosage": "alarmedosage",
	"ing_reappro": "ingrreappro",
	"commentaire": "commentaire",
	"dernier_dosage": "lastdosing",
	"log_interval": "loginterval",
	"option": "Options",

	"non_dose_stock_mini": "dosageimpossible_all",
	"diam_seringue_cobra": "param1",
	"inc_mg": "param2",
	"snif": "param3",
	"inc_purge": "param4",
	"volume_ml": "param5",
	"tol_calbibre": "param6",
	"petite_cal": "param7",
	"grande_cal": "param8",
	"cor_ouv": "param9",
	"cor_fer": "param10",
	"seuil_unitaire_control": "param11",
	"param12": "param12",
	"param13": "param13",
	"diam_seringue": "param14",
	"param15": "param15",
	"param16": "param16",
	"param17": "param17",
	"param18": "param18",
	"param19": "param19",
	"param20": "param20",
	"param21": "param21",
	"param22": "param22",
	"status_calibration": "param23",
	"param24": "param24",
	"param25": "param25",
	"param26": "param26",
	"param27": "param27",
	"param28": "param28",
	"param29": "param29",
	"param30": "param30",
	"param31": "param31",
	"param32": "param32",
	"param33": "param33",
	"param34": "param34",
	"param35": "param35",
	"param36": "param36",
	"param37": "param37",
	"param38": "param38",
	"param39": "param39",
	}
"""
CREATE TABLE `co1_paramseringue` (
  `IDseringue` int(11) NOT NULL AUTO_INCREMENT,
  `numseringue` smallint(3) NOT NULL DEFAULT '0',
  `type` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `nummodule` tinyint(4) NOT NULL DEFAULT '0',
  `IDingredient` int(10) unsigned NOT NULL DEFAULT '0',
  `visible` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `disponible` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `modedosage` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `toldosabspos` double NOT NULL DEFAULT '0',
  `toldosabsneg` double NOT NULL DEFAULT '0',
  `toldosrelpos` double NOT NULL DEFAULT '0',
  `toldosrelneg` double NOT NULL DEFAULT '0',
  `poidsmaximum` double NOT NULL DEFAULT '0',
  `poidsminimum` double NOT NULL DEFAULT '0',
  `aftererror` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `dosageimpossible_al` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `alarmereappro` double NOT NULL DEFAULT '0',
  `alarmemanque` double NOT NULL DEFAULT '0',
  `alarmedosage` double NOT NULL DEFAULT '0',
  `ingrreappro` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `commentaire` varchar(100) NOT NULL DEFAULT '0',
  `lastdosing` datetime NOT NULL DEFAULT '2000-01-01 00:00:00',
  `loginterval` int(10) unsigned NOT NULL DEFAULT '0',
  `Options` int(10) unsigned NOT NULL DEFAULT '0',
  `param1` double NOT NULL DEFAULT '0',
  `param2` double NOT NULL DEFAULT '0',
  `param3` double NOT NULL DEFAULT '0',
  `param4` double NOT NULL DEFAULT '0',
  `param5` double NOT NULL DEFAULT '0',
  `param6` double NOT NULL DEFAULT '0',
  `param7` double NOT NULL DEFAULT '0',
  `param8` double NOT NULL DEFAULT '0',
  `param9` double NOT NULL DEFAULT '0',
  `param10` double NOT NULL DEFAULT '0',
  `param11` double NOT NULL DEFAULT '0',
  `param12` double NOT NULL DEFAULT '0',
  `param13` double NOT NULL DEFAULT '0',
  `param14` double NOT NULL DEFAULT '0',
  `param15` double NOT NULL DEFAULT '0',
  `param16` double NOT NULL DEFAULT '0',
  `param17` double NOT NULL DEFAULT '0',
  `param18` double NOT NULL DEFAULT '0',
  `param19` double NOT NULL DEFAULT '0',
  `param20` double NOT NULL DEFAULT '0',
  `param21` double NOT NULL DEFAULT '0',
  `param22` double NOT NULL DEFAULT '0',
  `param23` double NOT NULL DEFAULT '0',
  `param24` double NOT NULL DEFAULT '0',
  `param25` double NOT NULL DEFAULT '0',
  `param26` double NOT NULL DEFAULT '0',
  `param27` double NOT NULL DEFAULT '0',
  `param28` double NOT NULL DEFAULT '0',
  `param29` double NOT NULL DEFAULT '0',
  `param30` double NOT NULL DEFAULT '0',
  `param31` double NOT NULL DEFAULT '0',
  `param32` double NOT NULL DEFAULT '0',
  `param33` double NOT NULL DEFAULT '0',
  `param34` double NOT NULL DEFAULT '0',
  `param35` double NOT NULL DEFAULT '0',
  `param36` double NOT NULL DEFAULT '0',
  `param37` double NOT NULL DEFAULT '0',
  `param38` double NOT NULL DEFAULT '0',
  `param39` double NOT NULL DEFAULT '0',
  `param40` double NOT NULL DEFAULT '0',
  `param41` double NOT NULL DEFAULT '0',
  `param42` double NOT NULL DEFAULT '0',
  `param43` double NOT NULL DEFAULT '0',
  `param44` double NOT NULL DEFAULT '0',
  `param45` double NOT NULL DEFAULT '0',
  `param46` double NOT NULL DEFAULT '0',
  `param47` double NOT NULL DEFAULT '0',
  `param48` double NOT NULL DEFAULT '0',
  `param49` double NOT NULL DEFAULT '0',
  `param50` double NOT NULL DEFAULT '0',
  `param51` double NOT NULL DEFAULT '0',
  `param52` double NOT NULL DEFAULT '0',
  `param53` double NOT NULL DEFAULT '0',
  `param54` double NOT NULL DEFAULT '0',
  `param55` double NOT NULL DEFAULT '0',
  `param56` double NOT NULL DEFAULT '0',
  `param57` double NOT NULL DEFAULT '0',
  `param58` double NOT NULL DEFAULT '0',
  `param59` double NOT NULL DEFAULT '0',
  `param60` double NOT NULL DEFAULT '0',
  `param61` double NOT NULL DEFAULT '0',
  `param62` double NOT NULL DEFAULT '0',
  `param63` double NOT NULL DEFAULT '0',
  `param64` double NOT NULL DEFAULT '0',
  `param65` double NOT NULL DEFAULT '0',
  `param66` double NOT NULL DEFAULT '0',
  `param67` double NOT NULL DEFAULT '0',
  `param68` double NOT NULL DEFAULT '0',
  `param69` double NOT NULL DEFAULT '0',
  `param70` double NOT NULL DEFAULT '0',
  `param71` double NOT NULL DEFAULT '0',
  `param72` double NOT NULL DEFAULT '0',
  `param73` double NOT NULL DEFAULT '0',
  `param74` double NOT NULL DEFAULT '0',
  `param75` double NOT NULL DEFAULT '0',
  PRIMARY KEY (`IDseringue`,`IDingredient`) USING BTREE
) ENGINE=MyISAM AUTO_INCREMENT=2001 DEFAULT CHARSET=latin1;
"""
V5_0_cobra = {
	"id": "IDseringue",
	"num_seringue": "numseringue",
	"type_seringue": "type",
	"num_module": "nummodule",
	"id_ingredient": "IDingredient",
	"visible": "visible",
	"disponible": "disponible",
	"mode_dosage": "modedosage",
	"tol_dose_abs_pos": "toldosabspos",
	"tol_dose_abs_neg": "toldosabsneg",
	"tol_dose_rel_pos": "toldosrelpos",
	"tol_dose_rel_neg": "toldosrelneg",
	"poids maxi": "poidsmaximum",
	"poids_mini": "poidsminimum",
	"mode_erreur": "aftererror",
	"non_dose_stock_mini": "dosageimpossible_al",
	"alarme_reappro": "alarmereappro",
	"alarme_manque": "alarmemanque",
	"alarme_dosage": "alarmedosage",
	"ing_reappro": "ingrreappro",
	"commentaire": "commentaire",
	"dernier_dosage": "lastdosing",
	"log_interval": "loginterval",
	"option": "Options",

	"diam_seringue_cobra": "param1",
	"inc_mg": "param2",
	"snif": "param3",
	"inc_purge": "param4",
	"volume_ml": "param5",
	"tol_calbibre": "param6",
	"petite_cal": "param7",
	"grande_cal": "param8",
	"cor_ouv": "param9",
	"cor_fer": "param10",
	"seuil_unitaire_control": "param11",
	"param12": "param12",
	"param13": "param13",
	"diam_seringue": "param14",
	"param15": "param15",
	"param16": "param16",
	"param17": "param17",
	"param18": "param18",
	"param19": "param19",
	"param20": "param20",
	"param21": "param21",
	"param22": "param22",
	"status_calibration": "param23",
	"param24": "param24",
	"param25": "param25",
	"param26": "param26",
	"param27": "param27",
	"param28": "param28",
	"param29": "param29",
	"param30": "param30",
	"param31": "param31",
	"param32": "param32",
	"param33": "param33",
	"param34": "param34",
	"param35": "param35",
	"param36": "param36",
	"param37": "param37",
	"param38": "param38",
	"param39": "param39",
	}

V5_13_cobra = {
	"id": "IDseringue",
	"num_seringue": "numseringue",
	"type_seringue": "type",
	"num_module": "nummodule",
	"id_ingredient": "IDingredient",
	"visible": "visible",
	"disponible": "disponible",
	"mode_dosage": "modedosage",
	"tol_dose_abs_pos": "toldosabspos",
	"tol_dose_abs_neg": "toldosabsneg",
	"tol_dose_rel_pos": "toldosrelpos",
	"tol_dose_rel_neg": "toldosrelneg",
	"poids maxi": "poidsmaximum",
	"poids_mini": "poidsminimum",
	"mode_erreur": "aftererror",
	"non_dose_stock_mini": "dosageimpossible_al",
	"alarme_reappro": "alarmereappro",
	"alarme_manque": "alarmemanque",
	"alarme_dosage": "alarmedosage",
	"ing_reappro": "ingrreappro",
	"commentaire": "commentaire",
	"dernier_dosage": "lastdosing",
	"log_interval": "loginterval",
	"option": "Options",

	"non_dose_stock_mini": "dosageimpossible_all",
	"diam_seringue_cobra": "param1",
	"inc_mg": "param2",
	"snif": "param3",
	"inc_purge": "param4",
	"volume_ml": "param5",
	"tol_calbibre": "param6",
	"petite_cal": "param7",
	"grande_cal": "param8",
	"cor_ouv": "param9",
	"cor_fer": "param10",
	"seuil_unitaire_control": "param11",
	"param12": "param12",
	"param13": "param13",
	"diam_seringue": "param14",
	"param15": "param15",
	"param16": "param16",
	"param17": "param17",
	"param18": "param18",
	"param19": "param19",
	"param20": "param20",
	"param21": "param21",
	"param22": "param22",
	"status_calibration": "param23",
	"param24": "param24",
	"param25": "param25",
	"param26": "param26",
	"param27": "param27",
	"param28": "param28",
	"param29": "param29",
	"param30": "param30",
	"param31": "param31",
	"param32": "param32",
	"param33": "param33",
	"param34": "param34",
	"param35": "param35",
	"param36": "param36",
	"param37": "param37",
	"param38": "param38",
	"param39": "param39",
	}


V4_3_colibri = {
	"id": "IDseringue",
	"num_seringue": "numseringue",
	"type_seringue": "type",
	"num_module": "nummodule",
	"id_ingredient": "IDingredient",
	"visible": "visible",
	"disponible": "disponible",
	"mode_dosage": "modedosage",
	"tol_dose_abs_pos": "toldosabspos",
	"tol_dose_abs_neg": "toldosabsneg",
	"tol_dose_rel_pos": "toldosrelpos",
	"tol_dose_rel_neg": "toldosrelneg",
	"poids maxi": "poidsmaximum",
	"poids_mini": "poidsminimum",
	"mode_erreur": "aftererror",
	"non_dose_stock_mini": "dosageimpossible_al",
	"alarme_reappro": "alarmereappro",
	"alarme_manque": "alarmemanque",
	"alarme_dosage": "alarmedosage",
	"ing_reappro": "ingrreappro",
	"commentaire": "commentaire",
	"dernier_dosage": "lastdosing",
	"log_interval": "loginterval",
	"option": "Options",

	"non_dose_stock_mini": "dosageimpossible_all",
	"param1": "param1",
	"param2": "param2",
	"param3": "param3",
	"inc_mg": "param4",
	"snif": "param5",
	"cor_ouv": "param6",
	"cor_fer": "param7",
	"param8": "param8",
	"param9": "param9",
	"param10": "param10",
	"param11": "param11",
	"param12": "param12",
	"param13": "param13",
	"diam_seringue": "param14",
	"param15": "param15",
	"param16": "param16",
	"param17": "param17",
	"param18": "param18",
	"param19": "param19",
	"param20": "param20",
	"param21": "param21",
	"param22": "param22",
	"status_calibration": "param23",
	"param24": "param24",
	"param25": "param25",
	"param26": "param26",
	"param27": "param27",
	"param28": "param28",
	"param29": "param29",
	"param30": "param30",
	"param31": "param31",
	"param32": "param32",
	"param33": "param33",
	"param34": "param34",
	"param35": "param35",
	"param36": "param36",
	"param37": "param37",
	"param38": "param38",
	"param39": "param39",
	}

V5_0_colibri = {
	"id": "IDseringue",
	"num_seringue": "numseringue",
	"type_seringue": "type",
	"num_module": "nummodule",
	"id_ingredient": "IDingredient",
	"visible": "visible",
	"disponible": "disponible",
	"mode_dosage": "modedosage",
	"tol_dose_abs_pos": "toldosabspos",
	"tol_dose_abs_neg": "toldosabsneg",
	"tol_dose_rel_pos": "toldosrelpos",
	"tol_dose_rel_neg": "toldosrelneg",
	"poids maxi": "poidsmaximum",
	"poids_mini": "poidsminimum",
	"mode_erreur": "aftererror",
	"non_dose_stock_mini": "dosageimpossible_al",
	"alarme_reappro": "alarmereappro",
	"alarme_manque": "alarmemanque",
	"alarme_dosage": "alarmedosage",
	"ing_reappro": "ingrreappro",
	"commentaire": "commentaire",
	"dernier_dosage": "lastdosing",
	"log_interval": "loginterval",
	"option": "Options",

	"non_dose_stock_mini": "dosageimpossible_all",
	"param1": "param1",
	"param2": "param2",
	"param3": "param3",
	"inc_mg": "param4",
	"snif": "param5",
	"cor_ouv": "param6",
	"cor_fer": "param7",
	"param8": "param8",
	"param9": "param9",
	"param10": "param10",
	"param11": "param11",
	"param12": "param12",
	"param13": "param13",
	"diam_seringue": "param14",
	"param15": "param15",
	"param16": "param16",
	"param17": "param17",
	"param18": "param18",
	"param19": "param19",
	"param20": "param20",
	"param21": "param21",
	"param22": "param22",
	"status_calibration": "param23",
	"param24": "param24",
	"param25": "param25",
	"param26": "param26",
	"param27": "param27",
	"param28": "param28",
	"param29": "param29",
	"param30": "param30",
	"param31": "param31",
	"param32": "param32",
	"param33": "param33",
	"param34": "param34",
	"param35": "param35",
	"param36": "param36",
	"param37": "param37",
	"param38": "param38",
	"param39": "param39",
	}

V5_13_colibri = {
	"id": "IDseringue",
	"num_seringue": "numseringue",
	"type_seringue": "type",
	"num_module": "nummodule",
	"id_ingredient": "IDingredient",
	"visible": "visible",
	"disponible": "disponible",
	"mode_dosage": "modedosage",
	"tol_dose_abs_pos": "toldosabspos",
	"tol_dose_abs_neg": "toldosabsneg",
	"tol_dose_rel_pos": "toldosrelpos",
	"tol_dose_rel_neg": "toldosrelneg",
	"poids maxi": "poidsmaximum",
	"poids_mini": "poidsminimum",
	"mode_erreur": "aftererror",
	"non_dose_stock_mini": "dosageimpossible_al",
	"alarme_reappro": "alarmereappro",
	"alarme_manque": "alarmemanque",
	"alarme_dosage": "alarmedosage",
	"ing_reappro": "ingrreappro",
	"commentaire": "commentaire",
	"dernier_dosage": "lastdosing",
	"log_interval": "loginterval",
	"option": "Options",

	"non_dose_stock_mini": "dosageimpossible_all",
	"param1": "param1",
	"param2": "param2",
	"param3": "param3",
	"inc_mg": "param4",
	"snif": "param5",
	"cor_ouv": "param6",
	"cor_fer": "param7",
	"param8": "param8",
	"param9": "param9",
	"param10": "param10",
	"param11": "param11",
	"param12": "param12",
	"param13": "param13",
	"diam_seringue": "param14",
	"param15": "param15",
	"param16": "param16",
	"param17": "param17",
	"param18": "param18",
	"param19": "param19",
	"param20": "param20",
	"param21": "param21",
	"param22": "param22",
	"status_calibration": "param23",
	"param24": "param24",
	"param25": "param25",
	"param26": "param26",
	"param27": "param27",
	"param28": "param28",
	"param29": "param29",
	"param30": "param30",
	"param31": "param31",
	"param32": "param32",
	"param33": "param33",
	"param34": "param34",
	"param35": "param35",
	"param36": "param36",
	"param37": "param37",
	"param38": "param38",
	"param39": "param39",
	}


V4_3_tex = {
	"id": "IDseringue",
	"num_seringue": "numseringue",
	"type_seringue": "type",
	"num_module": "nummodule",
	"id_ingredient": "IDingredient",
	"visible": "visible",
	"disponible": "disponible",
	"mode_dosage": "modedosage",
	"tol_dose_abs_pos": "toldosabspos",
	"tol_dose_abs_neg": "toldosabsneg",
	"tol_dose_rel_pos": "toldosrelpos",
	"tol_dose_rel_neg": "toldosrelneg",
	"poids maxi": "poidsmaximum",
	"poids_mini": "poidsminimum",
	"mode_erreur": "aftererror",
	"non_dose_stock_mini": "dosageimpossible_al",
	"alarme_reappro": "alarmereappro",
	"alarme_manque": "alarmemanque",
	"alarme_dosage": "alarmedosage",
	"ing_reappro": "ingrreappro",
	"commentaire": "commentaire",
	"dernier_dosage": "lastdosing",
	"log_interval": "loginterval",
	"option": "Options",

	"non_dose_stock_mini": "dosageimpossible_all",
	"param1": "param1",
	"param2": "param2",
	"param3": "param3",
	"inc_mg": "param4",
	"snif": "param5",
	"cor_ouv": "param6",
	"cor_fer": "param7",
	"param8": "param8",
	"param9": "param9",
	"param10": "param10",
	"param11": "param11",
	"param12": "param12",
	"param13": "param13",
	"diam_seringue": "param14",
	"param15": "param15",
	"param16": "param16",
	"param17": "param17",
	"param18": "param18",
	"param19": "param19",
	"param20": "param20",
	"param21": "param21",
	"param22": "param22",
	"status_calibration": "param23",
	"param24": "param24",
	"param25": "param25",
	"param26": "param26",
	"param27": "param27",
	"param28": "param28",
	"param29": "param29",
	"param30": "param30",
	"param31": "param31",
	"param32": "param32",
	"param33": "param33",
	"param34": "param34",
	"param35": "param35",
	"param36": "param36",
	"param37": "param37",
	"param38": "param38",
	"param39": "param39",
	}

V5_0_tex = {
	"id": "IDseringue",
	"num_seringue": "numseringue",
	"type_seringue": "type",
	"num_module": "nummodule",
	"id_ingredient": "IDingredient",
	"visible": "visible",
	"disponible": "disponible",
	"mode_dosage": "modedosage",
	"tol_dose_abs_pos": "toldosabspos",
	"tol_dose_abs_neg": "toldosabsneg",
	"tol_dose_rel_pos": "toldosrelpos",
	"tol_dose_rel_neg": "toldosrelneg",
	"poids maxi": "poidsmaximum",
	"poids_mini": "poidsminimum",
	"mode_erreur": "aftererror",
	"non_dose_stock_mini": "dosageimpossible_al",
	"alarme_reappro": "alarmereappro",
	"alarme_manque": "alarmemanque",
	"alarme_dosage": "alarmedosage",
	"ing_reappro": "ingrreappro",
	"commentaire": "commentaire",
	"dernier_dosage": "lastdosing",
	"log_interval": "loginterval",
	"option": "Options",

	"non_dose_stock_mini": "dosageimpossible_all",
	"param1": "param1",
	"param2": "param2",
	"param3": "param3",
	"inc_mg": "param4",
	"snif": "param5",
	"cor_ouv": "param6",
	"cor_fer": "param7",
	"param8": "param8",
	"param9": "param9",
	"param10": "param10",
	"param11": "param11",
	"param12": "param12",
	"param13": "param13",
	"diam_seringue": "param14",
	"param15": "param15",
	"param16": "param16",
	"param17": "param17",
	"param18": "param18",
	"param19": "param19",
	"param20": "param20",
	"param21": "param21",
	"param22": "param22",
	"status_calibration": "param23",
	"param24": "param24",
	"param25": "param25",
	"param26": "param26",
	"param27": "param27",
	"param28": "param28",
	"param29": "param29",
	"param30": "param30",
	"param31": "param31",
	"param32": "param32",
	"param33": "param33",
	"param34": "param34",
	"param35": "param35",
	"param36": "param36",
	"param37": "param37",
	"param38": "param38",
	"param39": "param39",
	}

V5_13_tex = {
	"id": "IDseringue",
	"num_seringue": "numseringue",
	"type_seringue": "type",
	"num_module": "nummodule",
	"id_ingredient": "IDingredient",
	"visible": "visible",
	"disponible": "disponible",
	"mode_dosage": "modedosage",
	"tol_dose_abs_pos": "toldosabspos",
	"tol_dose_abs_neg": "toldosabsneg",
	"tol_dose_rel_pos": "toldosrelpos",
	"tol_dose_rel_neg": "toldosrelneg",
	"poids maxi": "poidsmaximum",
	"poids_mini": "poidsminimum",
	"mode_erreur": "aftererror",
	"non_dose_stock_mini": "dosageimpossible_al",
	"alarme_reappro": "alarmereappro",
	"alarme_manque": "alarmemanque",
	"alarme_dosage": "alarmedosage",
	"ing_reappro": "ingrreappro",
	"commentaire": "commentaire",
	"dernier_dosage": "lastdosing",
	"log_interval": "loginterval",
	"option": "Options",

	"non_dose_stock_mini": "dosageimpossible_all",
	"param1": "param1",
	"param2": "param2",
	"param3": "param3",
	"inc_mg": "param4",
	"snif": "param5",
	"cor_ouv": "param6",
	"cor_fer": "param7",
	"param8": "param8",
	"param9": "param9",
	"param10": "param10",
	"param11": "param11",
	"param12": "param12",
	"param13": "param13",
	"diam_seringue": "param14",
	"param15": "param15",
	"param16": "param16",
	"param17": "param17",
	"param18": "param18",
	"param19": "param19",
	"param20": "param20",
	"param21": "param21",
	"param22": "param22",
	"status_calibration": "param23",
	"param24": "param24",
	"param25": "param25",
	"param26": "param26",
	"param27": "param27",
	"param28": "param28",
	"param29": "param29",
	"param30": "param30",
	"param31": "param31",
	"param32": "param32",
	"param33": "param33",
	"param34": "param34",
	"param35": "param35",
	"param36": "param36",
	"param37": "param37",
	"param38": "param38",
	"param39": "param39",
	}


V4_3_dopo = {
	"id": "IDseringue",
	"num_seringue": "numseringue",
	"type_seringue": "type",
	"num_module": "nummodule",
	"id_ingredient": "IDingredient",
	"visible": "visible",
	"disponible": "disponible",
	"mode_dosage": "modedosage",
	"tol_dose_abs_pos": "toldosabspos",
	"tol_dose_abs_neg": "toldosabsneg",
	"tol_dose_rel_pos": "toldosrelpos",
	"tol_dose_rel_neg": "toldosrelneg",
	"poids maxi": "poidsmaximum",
	"poids_mini": "poidsminimum",
	"mode_erreur": "aftererror",
	"non_dose_stock_mini": "dosageimpossible_al",
	"alarme_reappro": "alarmereappro",
	"alarme_manque": "alarmemanque",
	"alarme_dosage": "alarmedosage",
	"ing_reappro": "ingrreappro",
	"commentaire": "commentaire",
	"dernier_dosage": "lastdosing",
	"log_interval": "loginterval",
	"option": "Options",

	"non_dose_stock_mini": "dosageimpossible_all",
	"param1": "param1",
	"param2": "param2",
	"param3": "param3",
	"inc_mg": "param4",
	"snif": "param5",
	"cor_ouv": "param6",
	"cor_fer": "param7",
	"param8": "param8",
	"param9": "param9",
	"param10": "param10",
	"param11": "param11",
	"param12": "param12",
	"param13": "param13",
	"diam_seringue": "param14",
	"param15": "param15",
	"param16": "param16",
	"param17": "param17",
	"param18": "param18",
	"param19": "param19",
	"param20": "param20",
	"param21": "param21",
	"param22": "param22",
	"status_calibration": "param23",
	"param24": "param24",
	"param25": "param25",
	"param26": "param26",
	"param27": "param27",
	"param28": "param28",
	"param29": "param29",
	"param30": "param30",
	"param31": "param31",
	"param32": "param32",
	"param33": "param33",
	"param34": "param34",
	"param35": "param35",
	"param36": "param36",
	"param37": "param37",
	"param38": "param38",
	"param39": "param39",
	}

V5_0_dopo = {
	"id": "IDseringue",
	"num_seringue": "numseringue",
	"type_seringue": "type",
	"num_module": "nummodule",
	"id_ingredient": "IDingredient",
	"visible": "visible",
	"disponible": "disponible",
	"mode_dosage": "modedosage",
	"tol_dose_abs_pos": "toldosabspos",
	"tol_dose_abs_neg": "toldosabsneg",
	"tol_dose_rel_pos": "toldosrelpos",
	"tol_dose_rel_neg": "toldosrelneg",
	"poids maxi": "poidsmaximum",
	"poids_mini": "poidsminimum",
	"mode_erreur": "aftererror",
	"non_dose_stock_mini": "dosageimpossible_al",
	"alarme_reappro": "alarmereappro",
	"alarme_manque": "alarmemanque",
	"alarme_dosage": "alarmedosage",
	"ing_reappro": "ingrreappro",
	"commentaire": "commentaire",
	"dernier_dosage": "lastdosing",
	"log_interval": "loginterval",
	"option": "Options",

	"non_dose_stock_mini": "dosageimpossible_all",
	"param1": "param1",
	"param2": "param2",
	"param3": "param3",
	"inc_mg": "param4",
	"snif": "param5",
	"cor_ouv": "param6",
	"cor_fer": "param7",
	"param8": "param8",
	"param9": "param9",
	"param10": "param10",
	"param11": "param11",
	"param12": "param12",
	"param13": "param13",
	"diam_seringue": "param14",
	"param15": "param15",
	"param16": "param16",
	"param17": "param17",
	"param18": "param18",
	"param19": "param19",
	"param20": "param20",
	"param21": "param21",
	"param22": "param22",
	"status_calibration": "param23",
	"param24": "param24",
	"param25": "param25",
	"param26": "param26",
	"param27": "param27",
	"param28": "param28",
	"param29": "param29",
	"param30": "param30",
	"param31": "param31",
	"param32": "param32",
	"param33": "param33",
	"param34": "param34",
	"param35": "param35",
	"param36": "param36",
	"param37": "param37",
	"param38": "param38",
	"param39": "param39",
	}

V5_13_dopo = {
	"id": "IDseringue",
	"num_seringue": "numseringue",
	"type_seringue": "type",
	"num_module": "nummodule",
	"id_ingredient": "IDingredient",
	"visible": "visible",
	"disponible": "disponible",
	"mode_dosage": "modedosage",
	"tol_dose_abs_pos": "toldosabspos",
	"tol_dose_abs_neg": "toldosabsneg",
	"tol_dose_rel_pos": "toldosrelpos",
	"tol_dose_rel_neg": "toldosrelneg",
	"poids maxi": "poidsmaximum",
	"poids_mini": "poidsminimum",
	"mode_erreur": "aftererror",
	"non_dose_stock_mini": "dosageimpossible_al",
	"alarme_reappro": "alarmereappro",
	"alarme_manque": "alarmemanque",
	"alarme_dosage": "alarmedosage",
	"ing_reappro": "ingrreappro",
	"commentaire": "commentaire",
	"dernier_dosage": "lastdosing",
	"log_interval": "loginterval",
	"option": "Options",

	"non_dose_stock_mini": "dosageimpossible_all",
	"param1": "param1",
	"param2": "param2",
	"param3": "param3",
	"inc_mg": "param4",
	"snif": "param5",
	"cor_ouv": "param6",
	"cor_fer": "param7",
	"param8": "param8",
	"param9": "param9",
	"param10": "param10",
	"param11": "param11",
	"param12": "param12",
	"param13": "param13",
	"diam_seringue": "param14",
	"param15": "param15",
	"param16": "param16",
	"param17": "param17",
	"param18": "param18",
	"param19": "param19",
	"param20": "param20",
	"param21": "param21",
	"param22": "param22",
	"status_calibration": "param23",
	"param24": "param24",
	"param25": "param25",
	"param26": "param26",
	"param27": "param27",
	"param28": "param28",
	"param29": "param29",
	"param30": "param30",
	"param31": "param31",
	"param32": "param32",
	"param33": "param33",
	"param34": "param34",
	"param35": "param35",
	"param36": "param36",
	"param37": "param37",
	"param38": "param38",
	"param39": "param39",
	}


db_param_seringue_cobra = {"4.3" : V4_3_cobra, "5.0" : V5_0_cobra, "5.13" : V5_13_cobra}
db_param_seringue_colibri = {"4.3" : V4_3_colibri, "5.0" : V5_0_colibri, "5.13" : V5_13_colibri}
db_param_seringue_tex = {"4.3" : V4_3_tex, "5.0" : V5_0_tex, "5.13" : V5_13_tex}
db_param_seringue_dopo = {"4.3" : V4_3_dopo, "5.0" : V5_0_dopo, "5.13" : V5_13_dopo}

def get_db_param_seringue_cobra(version, param):
	return db_param_seringue_cobra[version][param]

def get_db_param_seringue_colibri(version, param):
	return param_db_seringue_colibri[version][param]

def get_db_param_seringue_tex(version, param):
	return db_param_seringue_tex[version][param]

def get_db_param_seringue_dopo(version, param):
	return db_param_seringue_dopo[version][param]


"""
dico_paramseringue_by_col_5_0_colibri = {
	"dosageimpossible_all" : "non_dose_stock_mini",
	"param1": "param1",
	"param2": "param2",
	"param3": "param3",
	"param4": "inc_mg",
	"param5": "snif",
	"param6": "cor_ouv",
	"param7": "cor_fer",
	"param8": "param8",
	"param9": "param9",
	"param10": "param10",
	"param11": "param11",
	"param12": "param12",
	"param13": "param13",
	"param14": "diam_seringue_colibri",
	"param15": "param15",
	"param16": "param16",
	"param17": "param17",
	"param18": "param18",
	"param19": "param19",
	"param20": "param20",
	"param21": "param21",
	"param22": "param22",
	"param23": "status_calibration",
	"param24": "param24",
	"param25": "param25",
	"param26": "param26",
	"param27": "param27",
	"param28": "param28",
	"param29": "param29",
	"param30": "param30",
	"param31": "param31",
	"param32": "param32",
	"param33": "param33",
	"param34": "param34",
	"param35": "param35",
	"param36": "param36",
	"param37": "param37",
	"param38": "param38",
	"param39": "param39",
	}

dico_paramseringue_by_col_5_0_cobra = {
	"dosageimpossible_all" : "non_dose_stock_mini",
	"param1": "diam_seringue_cobra",
	"param2": "inc_mg",
	"param3": "snif",
	"param4": "inc_purge",
	"param5": "volume_ml",
	"param6": "tol_calbibre",
	"param7": "petite_cal",
	"param8": "grande_cal",
	"param9": "correc_ouvr",
	"param10": "correc_ferm",
	"param11": "seuil_unitaire_control",
	"param12": "param12",
	"param13": "param13",
	"param14": "diam",
	"param15": "param15",
	"param16": "param16",
	"param17": "param17",
	"param18": "param18",
	"param19": "param19",
	"param20": "param20",
	"param21": "param21",
	"param22": "param22",
	"param23": "status_calibration",
	"param24": "param24",
	"param25": "param25",
	"param26": "param26",
	"param27": "param27",
	"param28": "param28",
	"param29": "param29",
	"param30": "param30",
	"param31": "param31",
	"param32": "param32",
	"param33": "param33",
	"param34": "param34",
	"param35": "param35",
	"param36": "param36",
	"param37": "param37",
	"param38": "param38",
	"param39": "param39",
	}
"""
